In [1]:
import numpy as np
import pandas as pd

In [ ]:
data = [10, 20, 30, 40, 50, 60]

mean = np.mean(data)
median = np.median(data)
variance = np.var(data)

mean, median, variance


(np.float64(35.0), np.float64(35.0), np.float64(291.6666666666667))

In [4]:
# Probability of getting even number from list
numbers = [1, 2, 3, 4, 5, 6]

even = [n for n in numbers if n % 2 == 0]

probability_even = len(even) / len(numbers)
probability_even


0.5

In [5]:
data = {
    "Hours_Studied": [2, 4, 6, 8, 10],
    "Marks": [40, 50, 65, 75, 90]
}

df = pd.DataFrame(data)

df.corr()


,Hours_Studied,Marks
Hours_Studied,1.000000,0.997609
Marks,0.997609,1.000000


In [6]:
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

vector_sum = vector_a + vector_b
dot_product = np.dot(vector_a, vector_b)

vector_sum, dot_product


(array([5, 7, 9]), np.int64(32))

In [10]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

matrix_add = matrix_a + matrix_b
matrix_mul = np.dot(matrix_a, matrix_b)

matrix_add, matrix_mul


(array([[ 6,  8],
        [10, 12]]),
 array([[19, 22],
        [43, 50]]))

### Statistics & Math for ML – Concept Notes

- Mean: Average value
- Median: Middle value
- Variance: Measure of spread
- Probability: Likelihood of an event
- Correlation: Relationship between variables
- Linear Algebra: Foundation of ML models
